apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: default
type: Opaque
data:
  db-username: dXNlcl9zZXJ2aWNlX3VzZXI=
  db-password: c2VjdXJlMTIz
  jwt-secret: MTVlYzRmNDA2M2MwMzA1NWM1ZTk0OTEyMmU4YWQxZWU2MGVkYjQ3MTBiNWJjNDQ4Y2FlZTFkZmFiZTMxZTYzNw==
